### ISSUE TITLE
App now crashes after latest update 

### ISSUE THREAD

**Issue by doogie544** [flathub/com.protonvpn.www#115]
version:
```
 Commit: 028fabcb5da917a779e35e3aa350958411319840451b445e038776197e68a767
    Parent: 6e3f0e290ce3a3f304cef73ae1738f4aab3645cd2673962020ee9c691b576de7
   Subject: Update poetry_core-1.7.0.tar.gz to 1.8.1 (#114) (08b1a34a)
      Date: 2023-11-02 15:53:26 +0000
```

App crashes with the following output

```
flatpak run com.protonvpn.www 
Traceback (most recent call last):
  File "/app/bin/protonvpn-app", line 5, in <module>
    from proton.vpn.app.gtk.__main__ import main
  File "/app/lib/python3.11/site-packages/proton/vpn/app/gtk/__main__.py", line 26, in <module>
    from proton.vpn.app.gtk.app import App
  File "/app/lib/python3.11/site-packages/proton/vpn/app/gtk/app.py", line 27, in <module>
    from proton.vpn.app.gtk.controller import Controller
  File "/app/lib/python3.11/site-packages/proton/vpn/app/gtk/controller.py", line 42, in <module>
    from proton.vpn.app.gtk.utils import semver
  File "/app/lib/python3.11/site-packages/proton/vpn/app/gtk/utils/semver.py", line 21, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging.version'
```

rolling back to commit 
```

    Commit: 6e3f0e290ce3a3f304cef73ae1738f4aab3645cd2673962020ee9c691b576de7
   Subject: Update charset-normalizer-3.3.1.tar.gz to 3.3.2 (#112) (7c82c8ca)
      Date: 2023-11-01 14:11:00 +0000
```

and the app is once again working as expected.  

Before rolling back I tried reinstalling and then removing and clean installing while removing user data.  Only rolling back to the previous commit allows the app to work

**Comment by doogie544** [comment]
Yes, with exactly the same errors word for word

```
File "/app/bin/protonvpn-app", line 5, in <module>
    from proton.vpn.app.gtk.__main__ import main
  File "/app/lib/python3.11/site-packages/proton/vpn/app/gtk/__main__.py", line 26, in <module>
    from proton.vpn.app.gtk.app import App
  File "/app/lib/python3.11/site-packages/proton/vpn/app/gtk/app.py", line 27, in <module>
    from proton.vpn.app.gtk.controller import Controller
  File "/app/lib/python3.11/site-packages/proton/vpn/app/gtk/controller.py", line 42, in <module>
    from proton.vpn.app.gtk.utils import semver
  File "/app/lib/python3.11/site-packages/proton/vpn/app/gtk/utils/semver.py", line 21, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging.version'
```
