### ISSUE TITLE
Broken on Fedora Silverblue

### ISSUE THREAD

**Issue by storopoli** [flathub/com.protonvpn.www#2]
![image](https://user-images.githubusercontent.com/43353831/227801709-6b66d2e1-f6b8-488f-af56-540dfb3fb09c.png)

How do I debug it for you?

**Comment by VarLad** [comment]
Can confirm the exact same on Fedora Silverblue as well

**Comment by njam** [comment]
I have the same problem on Fedora Silverblue.

The app's `protonvpn-gui.log` has this error:
```
2023-03-31 20:11:44,181 — dashboard.py — INFO —on_country_connect:329 — Preparing to connect to country "CH"
2023-03-31 20:11:44,182 — dashboard.py — INFO —connect:386 — Setting up connection
2023-03-31 20:11:44,687 — dashboard.py — ERROR —connect:460 — Support for given configuration is not implemented
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/protonvpn_gui/view_model/dashboard.py", line 395, in connect
    server = protonvpn.setup_connection(
  File "/app/lib/python3.10/site-packages/protonvpn_nm_lib/api.py", line 158, in setup_connection
    self._env.connection_backend.setup(**data)
  File "/app/lib/python3.10/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client.py", line 51, in setup
    connection, protocol_implementation = NMPlugin.import_vpn_config(
  File "/app/lib/python3.10/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/plugin/nm_plugin.py", line 31, in import_vpn_config
    raise NotImplementedError(
NotImplementedError: Support for given configuration is not implemented
```

Which seems to result from the [protonvpn-nm-lib code](https://github.com/ProtonVPN/protonvpn-nm-lib/blob/cad0f6700696486fda18ded09abf9e7d7fd212d1/protonvpn_nm_lib/core/connection_backend/nm_client/plugin/nm_plugin.py#L31).

**Comment by enkodr** [comment]
I have `NetworkManager-openvpn` package installed but I got the same error shown above

**Comment by njam** [comment]
Yeah I also have `NetworkManager-openvpn` installed.

**Comment by enkodr** [comment]
@proletarius101 Installing with `--user` works

**Comment by storopoli** [comment]
Yes! Thank you installing with `--user` works.
