### ISSUE TITLE
Protonvpn will not launch

### ISSUE THREAD

**Issue by RagglenLove** [flathub/com.protonvpn.www#276]
My system is Xubuntu 24.04 and when I launch it via Terminal, here's the result:

```
flatpak run com.protonvpn.www
Traceback (most recent call last):
  File "/app/bin/protonvpn-app", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/proton/vpn/app/gtk/__main__.py", line 34, in main
    controller = Controller.get(executor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/proton/vpn/app/gtk/controller.py", line 59, in get
    executor.submit(controller.initialize_vpn_connector).result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/lib/python3.11/site-packages/proton/vpn/app/gtk/controller.py", line 94, in initialize_vpn_connector
    self._connector = await self._api.get_vpn_connector()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/proton/vpn/core/api.py", line 57, in get_vpn_connector
    settings = await self.load_settings()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/proton/vpn/core/api.py", line 68, in load_settings
    user_tier = self._session_holder.session.vpn_account.max_tier
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'max_tier'

**Comment by mattgatto** [comment]
I'm seeing this too on Fedora 40.

  File "/usr/lib/python3.12/site-packages/proton/vpn/core/api.py", line 81, in load_settings
    user_tier = self._session_holder.session.vpn_account.max_tier
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'max_tier'

I tried logging out of the website because somebody said that could cause the problem? When you say, "try logging in again" you mean, to the protonvpn website?

**Comment by mattgatto** [comment]
BTW, I'm using Fedora dnf beta repo, not the flatpak, but anyway, it started working after doing dnf update on my system today. Apparently some older proton libraries were replaced during the update, which changed the following proton libraries:

proton-vpn-gnome-desktop                            0.5.0-1.fc40                                             protonvpn-fedora-unstable    
proton-vpn-gtk-app                                         4.4.5-1.fc40                                             protonvpn-fedora-unstable   
python3-proton-core                                       0.3.1-1.fc40                                             protonvpn-fedora-unstable  
python3-proton-vpn-api-core                        0.33.11-1.fc40                                           protonvpn-fedora-unstablek
python3-proton-vpn-network-manager      0.6.3-1.fc40                                             protonvpn-fedora-unstable  

    replacing  python3-proton-vpn-network-manager-openvpn.noarch 0.1.0-1.fc40
    replacing  python3-proton-vpn-network-manager-wireguard.noarch 0.4.1-1.fc40

2024-09-10T12:21:54-0400 DEBUG ---> Package python3-proton-core.noarch 0.2.0-1.fc40 will be upgraded
2024-09-10T12:21:54-0400 DEBUG ---> Package python3-proton-core.noarch 0.3.1-1.fc40 will be an upgrade
2024-09-10T12:21:54-0400 DEBUG ---> Package python3-proton-vpn-api-core.noarch 0.32.2-1.fc40 will be upgraded
2024-09-10T12:21:54-0400 DEBUG ---> Package python3-proton-vpn-api-core.noarch 0.33.11-1.fc40 will be an upgrade
2024-09-10T12:21:54-0400 DEBUG ---> Package python3-proton-vpn-network-manager-openvpn.noarch 0.1.0-1.fc40 will be obsoleted
2024-09-10T12:21:54-0400 DEBUG ---> Package python3-proton-vpn-network-manager-wireguard.noarch 0.4.1-1.fc40 will be obsoleted
2024-09-10T12:21:54-0400 DEBUG ---> Package python3-proton-vpn-network-manager.noarch 0.5.2-1.fc40 will be upgraded
2024-09-10T12:21:54-0400 DEBUG ---> Package python3-proton-vpn-network-manager.noarch 0.6.3-1.fc40 will be an upgrade
